apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnosis-iam
spec:
  template:
    spec:
      containers:
      - name: gnosis-iam
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "staging"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnosis-api-gateway
spec:
  template:
    spec:
      containers:
      - name: gnosis-api-gateway
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "staging"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnosis-structure
spec:
  template:
    spec:
      containers:
      - name: gnosis-structure
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "staging"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnosis-scheduler
spec:
  template:
    spec:
      containers:
      - name: gnosis-scheduler
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "staging"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnosis-journal-command
spec:
  template:
    spec:
      containers:
      - name: gnosis-journal-command
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "staging"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnosis-analytics-query
spec:
  template:
    spec:
      containers:
      - name: gnosis-analytics-query
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "staging"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnosis-notifier
spec:
  template:
    spec:
      containers:
      - name: gnosis-notifier
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "staging"
