apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opengnosis-staging

namePrefix: staging-

commonLabels:
  environment: staging

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

replicas:
  - name: gnosis-iam
    count: 2
  - name: gnosis-api-gateway
    count: 2
  - name: gnosis-structure
    count: 2
  - name: gnosis-scheduler
    count: 2
  - name: gnosis-journal-command
    count: 2
  - name: gnosis-analytics-query
    count: 2
  - name: gnosis-notifier
    count: 2
